#!/usr/bin/env bash

# Script to install dependencies for cross compilation

dpkg --add-architecture $CROSS_DEB_ARCH

apt-get update
apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH openssl:$CROSS_DEB_ARCH
