[package]
name = "ex_tokenizers"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ex_tokenizers"
path = "src/lib.rs"
crate-type = ["cdylib"]

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dependencies]
anyhow = "1"
rustler = "0.25.0"
thiserror = "1"
tokenizers = "0.11.3"
