[package]
name = "ex_tokenizers"
version = "0.1.2"
authors = []
edition = "2018"

[lib]
name = "ex_tokenizers"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
rustler = "0.25.0"
thiserror = "1"
tokenizers = "0.11.3"
openssl = { version = "0.10", optional = true }

[features]
static_openssl = ["openssl/vendored"]
