name: Build precompiled NIFs

on:
  push:
    branches:
      - main
    paths:
      # Just run on main branch if "native" path changed. Tags will always run.
      - "native/**"
      # Also run in case there is any changes to this file.
      - ".github/workflows/release.yml"
    tags:
      - "*"

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        nif: ["2.15", "2.16"]
        job:
          - { target: aarch64-apple-darwin, os: macos-13 }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-22.04, use-cross: true }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-22.04, use-cross: true }
          - { target: arm-unknown-linux-gnueabihf, os: ubuntu-22.04, use-cross: true }
          - { target: riscv64gc-unknown-linux-gnu, os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-apple-darwin, os: macos-13 }
          - { target: x86_64-pc-windows-gnu, os: windows-2022 }
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-22.04, use-cross: true }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Extract crate information
        shell: bash
        run: |
          # Get the project version from mix.exs
          echo "PROJECT_VERSION=$(sed -n 's/^  @version "\(.*\)"/\1/p' mix.exs | head -n1)" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.0.1
        with:
          nif-version: ${{ matrix.nif }}
          project-dir: "native/ex_tokenizers"
          project-name: ex_tokenizers
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          use-cross: ${{ matrix.job.use-cross }}

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.build-crate.outputs.file-path }}
        if: startsWith(github.ref, 'refs/tags/')
